# application-example.properties
# COPIA este archivo y renómbralo a application.properties
# Luego pon TUS keys reales

spring.application.name=Java

# Configuración del clima (necesitas registrarte en OpenWeatherMap)
weather.api.key=TU_API_KEY_AQUI
weather.api.baseurl=https://api.openweathermap.org/data/2.5